export default {
  AUTH_ENDPOINTS: {
    REFRESH_TOKEN: "/api/v1/auth/washing",
    LOGIN: "/api/v1/auth/login",
    LOGOUT: "/api/v1/auth/logout",
    REGISTER: "/api/v1/auth/register",
    VERIFY: "/api/v1/auth/verify-email",
    FORGOT_PASSWORD: "/api/v1/auth/forgot-password",
    RESET_PASSWORD: "api/v1/auth/reset-password",
    ME: "/api/v1/auth/me",
    UPDATE_ME: "/api/v1/auth/me",
  },
  USER_ENDPOINTS: {
    PROFILE: "/api/v1/user/profile",
    GET_ALL_USERS: "/api/v1/user",
    BAN_USER: (id: string) => `/api/v1/user/${id}/ban`,
    UNBAN_USER: (id: string) => `/api/v1/user/${id}/unban`,
  },
  ROLE_ENDPOINTS: {
    GET_ALL: "/api/v1/role/all",
    GET_ALL_PAGINATED: "/api/v1/role",
    UPDATE_ROLE: "/api/v1/role",
    CREATE_ROLE: "/api/v1/role",
    DELETE_ROLE: (id: string) => `/api/v1/role/${id}/hard`,
    GET_ROLE_BY_ID: "/api/v1/role",
  },
  PERMISSION_ENDPOINTS: {
    GET_ALL: "/api/v1/permission/all",
    GET_ALL_PAGINATED: "/api/v1/permission",
    UPDATE_PERMISSION: "/api/v1/permission",
    CREATE_PERMISSION: "/api/v1/permission",
    DELETE_PERMISSION: (id: string) => `/api/v1/permission/${id}/hard`,
  },
  ACTION_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/action",
    GET_BY_ID: (id: string) => `/api/v1/action/${id}`,
    CREATE: "/api/v1/action",
    UPDATE: (id: string) => `/api/v1/action/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/action/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/action/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/action/${id}/restore`,
  },
  ENTITY_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/entity",
    GET_BY_ID: (id: string) => `/api/v1/entity/${id}`,
    CREATE: "/api/v1/entity",
    UPDATE: (id: string) => `/api/v1/entity/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/entity/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/entity/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/entity/${id}/restore`,
  },
  INTENT_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/intent",
    GET_BY_ID: (id: string) => `/api/v1/intent/${id}`,
    CREATE: "/api/v1/intent",
    UPDATE: (id: string) => `/api/v1/intent/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/intent/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/intent/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/intent/${id}/restore`,
  },
  RESPONSE_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/my-response",
    GET_BY_ID: (id: string) => `/api/v1/my-response/${id}`,
    CREATE: "/api/v1/my-response",
    UPDATE: (id: string) => `/api/v1/my-response/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/my-response/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/my-response/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/my-response/${id}/restore`,
  },
  RULE_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/rule",
    GET_BY_ID: (id: string) => `/api/v1/rule/${id}`,
    CREATE: "/api/v1/rule",
    UPDATE: (id: string) => `/api/v1/rule/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/rule/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/rule/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/rule/${id}/restore`,
  },
  UQUESTION_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/uquestion",
    GET_BY_ID: (id: string) => `/api/v1/uquestion/${id}`,
    CREATE: "/api/v1/uquestion",
    UPDATE: (id: string) => `/api/v1/uquestion/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/uquestion/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/uquestion/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/uuestion/${id}/restore`,
  },
  CHATBOT_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/chatbot",
    GET_BY_ID: (id: string) => `/api/v1/chatbot/${id}`,
    CREATE: "/api/v1/chatbot",
    UPDATE: (id: string) => `/api/v1/chatbot/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/chatbot/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/chatbot/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/chatbot/${id}/restore`,

    GET_MODELS_LIST: (id: string) => `/api/v1/chatbot/${id}/models`,
    GET_ACTIONS_LIST: (id: string) => `/api/v1/chatbot/${id}/actions`,
    HEALTH_CHECK: (id: string) => `/api/v1/chatbot/${id}/health`,
    SEND_MODEL: (id: string) => `/api/v1/chatbot/${id}/send`,
    RUN_MODEL: (id: string) => `/api/v1/chatbot/${id}/run`,
    PUSH_ACTION: (id: string) => `/api/v1/chatbot/${id}/push-action`,
    GET_MY_MODELS: (id: string) => `/api/v1/chatbot/${id}/my-models`,
    GET_RASA_ACTIONS_LIST: (id: string) => `/api/v1/chatbot/${id}/actions`,
    RUN_ACTION: (id: string) => `/api/v1/chatbot/${id}/run-actions`,

  },

  STORY_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/story",
    GET_BY_ID: (id: string) => `/api/v1/story/${id}`,
    CREATE: "/api/v1/story",
    UPDATE: (id: string) => `/api/v1/story/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/story/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/story/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/story/${id}/restore`,
  },

  SLOT_ENDPOINTS: {
    GET_ALL_PAGINATED: "/api/v1/slot",
    GET_BY_ID: (id: string) => `/api/v1/slot/${id}`,
    CREATE: "/api/v1/slot",
    UPDATE: (id: string) => `/api/v1/slot/${id}`,
    HARD_DELETE: (id: string) => `/api/v1/slot/${id}/hard`,
    SOFT_DELETE: (id: string) => `/api/v1/slot/${id}/soft`,
    RESTORE: (id: string) => `/api/v1/slot/${id}/restore`,
  },

  TRAINING_ENDPOINTS: {
    TRAIN_MODEL: (chatbotId: string) => `/api/v1/chatbot/${chatbotId}/train`,
    GET_MODELS: "/api/v1/my-model",
    GET_MODEL_BY_ID: (id: string) => `/api/v1/my-model/${id}`,
  },
} as const;
